
version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_app
    working_dir: /var/www/link-boleto
    volumes:
      - ./:/var/www/link-boleto
    depends_on:
      - pgsql
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_queue
    working_dir: /var/www/link-boleto
    command: php artisan queue:work --tries=3 --timeout=60
    volumes:
      - ./:/var/www/link-boleto
    depends_on:
      - pgsql
      - app
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: boleto_scheduler
    working_dir: /var/www/link-boleto
    command: php artisan schedule:work
    volumes:
      - ./:/var/www/link-boleto
    depends_on:
      - app
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: boleto_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #mapeia o código fonte da aplicação 1 para o container do nginx
      - ./:/var/www/link-boleto
      
      #mapeia o código fonte da aplicação 2 para o container do nginx
      - ../link-boleto-campanha:/var/www/link-boleto-campanha

      #mapeia o código da aplicação 3 para o container do nginx
      - ../projeto-conta-azul:/var/www/projeto-conta-azul

      #mapeia o certificado de homologação do conta azul para o container do nginx
      - ../projeto-conta-azul/cert/efi:/etc/nginx/certs:ro

      - ./docker/nginx/pro/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - laravel
      - web  # <--- Adicione a rede externa aqui

  pgsql:
    image: postgres:16
    container_name: boleto_pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
  web:
    external: true