# =========================================
# APP 1 - EVO BOLETOS
# =========================================

server {
    listen 80;
    server_name evoboletos.mundoevogard.com;
    
    # Redireciona tudo que entrar no HTTP (80) para o HTTPS (443)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # <--- ESSENCIAL: ouvir na porta 443 com SSL
    server_name evoboletos.mundoevogard.com;

    client_max_body_size 500M;

    # Certificados mapeados via volume do Docker
    ssl_certificate /etc/letsencrypt/live/evoboletos.mundoevogard.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/evoboletos.mundoevogard.com/privkey.pem;

    # Otimizações recomendadas de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/link-boleto/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}


# =========================================
# APP 2 - EVO BOLETOS CAMPANHA
# =========================================

server {
    listen 80;
    server_name campanha.mundoevogard.com;
    
    # Redireciona tudo que entrar no HTTP (80) para o HTTPS (443)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # <--- ESSENCIAL: ouvir na porta 443 com SSL
    server_name campanha.mundoevogard.com;

    client_max_body_size 500M;

    # Certificados mapeados via volume do Docker
    ssl_certificate /etc/letsencrypt/live/campanha.mundoevogard.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/campanha.mundoevogard.com/privkey.pem;

    # Otimizações recomendadas de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/link-boleto-campanha/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app_campanha:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/link-boleto-campanha/public$fastcgi_script_name;
    }
}

# =========================================
# APP 3 - EVO BOLETOS FINANCEIRO
# =========================================

server {
    listen 80;
    server_name financeiro.mundoevogard.com;
    
    # Redireciona tudo que entrar no HTTP (80) para o HTTPS (443)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # <--- ESSENCIAL: ouvir na porta 443 com SSL
    server_name financeiro.mundoevogard.com;

    client_max_body_size 500M;

    # Certificados mapeados via volume do Docker
    ssl_certificate /etc/letsencrypt/live/financeiro.mundoevogard.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/financeiro.mundoevogard.com/privkey.pem;

    # Otimizações recomendadas de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /var/www/projeto-conta-azul/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app_conta_azul:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/projeto-conta-azul/public$fastcgi_script_name;
    }
}